export const penguinQuotes = [
  "Do things tired",
  "It's all stories",
  "Sometimes you just have to wing it.",
  "Tame the lizard",
  "Don't be the bottleneck",
  "Automate it!",
  "I love being myself! I can't wait to do it tomorrow!",
  "I'm not forced to do things, I simply do them.",
  "Start tasks with no intention to finish them.",
  "Feeling bad isn't load bearing.",
  "Work-life-balance is bad, you want work-life-maximization.",
  "Write everything down",
  "Don't make up excuses unless you're looking for a solution.",
  "It's not that hard",
  "It's not that deep",
  "It's easy actually",
  "Laziness is productivity, your terminal goal is to work less.",
  "Take care of your body, especially your brain!",
  "Are you doing this for you or for someone else?",
  "Focus on the process",
  "Start working first, then learn",
  "Start doing things, then think",
  "Eat the frog!",
  "Leverage reverse Parkinson's law",
  "Remove friction",
  "Say hi to your friends",
  "Go on an adventure today",
  "You aren't enduring hardship because you're brave and strong, you're just silly and don't give a shit.",
  "Being productive is the best way to distract yourself from how shit you feel.",
  "Problems are irrelevant, think of solutions.",
  "Failure means you were successful at trying new things! Good job!",
  "Just come up with as many bad ideas as possible.",
  "Move fast and break things!",
  "Enjoy being proven wrong",
  "Don't be attached to your opinions",
  "You can't win if you're not prepared to lose!",
  "Try time tracking",
  "Look for happiness in the present, not the future",
  "Celebrate small wins",
  "Bad feelings are optional",
  "Romanticise your own life",
  "You don't deserve anything, but it's ok to have things you don't deserve",
  "Find convoluted reasons for why whatever emotion you're feeling is good for productivity",
  "Don't be attached to outcomes",
  "Stop doing things you know you shouldn't be doing",
  "Doing the right thing isn't harder, the lack of guilt outweighs the effort",
  "Approach every task as a speedrun",
  "Never expect anyone's help, but ask anyway",
  "Microdose capitalism",
  "Take a mental vacation once in a while :)",
  "Notice minor annoyances and google how to fix them",
  "Question everything",
  "Improve your environment today",
  "Want less",
  "Optimize something today",
  "Move mountains with a breath",
  "Work for the audience, try to impress them",
  "What advice would you give to a friend if they were in your shoes?",
  "Strive for growth",
  "Delay gratification",
  "Someone you hate worked out today, did you?",
  "In the pursuit of knowledge, every day something is added. In the practice of wisdom, every day something is dropped.",
  "Where would you want to be in the future? Are you working towards it?",
  "Be deliberate and mindful today",
  "Try to constantly feel bliss today",
  "Don't feel guilty today",
  "Pain is just pain",
  "Everything is no big deal",
  "Set deadlines for yourself",
  "Give someone a compliment today",
  "Stop signalling",
  "Have good posture today",
  "Things that are good for you are fun and easy. Things that are bad for you are unfun and hard.",
  "If you had infinite time, what would you do with it? why aren't you doing that now?",
  "feeling terrible is kinda fine",
  "Break tasks into smaller tasks",
  "Start tasks when you feel good and leave them unfinished",
  "Work in a novel environment today",
  "You are what you do",
  "Consider the risks of not doing something",
  "If you don't fail regularly, you aren't taking enough risks",
];
